name: sample
version: 0.0.0
synopsis: Sample Haskell project
dependencies:
  - base >= 4.9 && <5

library:
  source-dirs: app

executables:
  hello:
    main: app/Main.hs
tests:
  test:
    main: app/Main.hs
    source-dirs: app
    dependencies:
      - hspec
    build-tools: hspec-discover


